# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11807e310aa04e54ac35d55b7f382068c3fd61cd2516a64a96d1a50f561984fb2dc26cd1d646358b337e4bd9ff382f0565c94bde9d0b66fdcae2f38a2c4cd973

test:
  secret_key_base: 8a83c7ec0648e1daac2e08bd4917feb2e7c719421552400b7fc589b4199c67e7c0cb1be0a690943c7dc0905d5521eabdf748b9402ef3fb288062bc420b0b004b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
